### ISSUE TITLE
Siopao forbits handlers that return a promise, although the bun server supports them

### ISSUE THREAD

**Issue by StanislavNikolov** [wobsoriano/siopao#1]
https://github.com/wobsoriano/siopao/blob/main/src/types.ts#L15

If replace you `Response` with `Response | Promise<Response>` in types.ts:15, typescript will no longer complain about this otherwise valid code:

```js
app.get("/test", async (req) => {
	await Bun.sleep(2000);
	return new Response("ok");
});
```

**Comment by wobsoriano** [comment]
Happy to accept a PR!
